config/routes.rb
Rails.application.routes.draw do
  root 'pages#welcome'
  get '/contact' => 'pages#contact'
  get '/about' => 'pages#about'
  get '/work' => 'pages#work'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def welcome
  end
  def contact
  end
  def work
  end
  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Portfolio</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link href="https://fonts.googleapis.com/css?family=Roboto:100,300,500,700" rel="stylesheet">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
  <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
</head>
<body>
	<header class="nav navbar">
    <div class="navbar-class">
      <div class="container">
        <ul class="navbar-ul">
          <li><%= link_to "Home", root_path, class: 'home_links' %></li>
          <li><%= link_to "Work", work_path, class: 'home_links' %></li>
          <li><%= link_to "About", about_path, class: 'home_links' %></li>
          <li><%= link_to "Contact", contact_path, class: 'home_links' %></li>
        </ul>
      </div>
    </div>
  </header>
	<%= yield %>

</body>
  <footer>
    <a href="https://github.com/", class="footer_icons">
      	<i class="fa fa-github fa-3x" aria-hidden="true"></i>
    </a>
    <a href="http://www.dailymail.co.uk/ushome/index.html", class="footer_icons">
      	<i class="fa fa-envelope fa-3x" aria-hidden="true"></i>
    </a>
    <a href="http://stackoverflow.com/", class="footer_icons">
      	<i class="fa fa-stack-overflow fa-3x" aria-hidden="true"></i>
    </a>
      <i class="fa fa-copyright" aria-hidden="true"> Caleb Meacham</i>
  </footer>
</html>

app/views/pages/about.html.erb
<!DOCTYPE html>
<html>
  <header>
  </header>
  <body>
    <h1>test</h1>
  </body>
</html>

app/views/pages/contact.html.erb
<!DOCTYPE html>
<html>
  <header>
  </header>
  <body>
    <h1>test</h1>
  </body>
</html>

app/views/pages/welcome.html.erb
<!DOCTYPE HTML>
<html>
  <head>
  </head>
  <body>
  	<div class="home_banner">
      <div class="home_image">
      <img src="http://media.spokesman.com/photos/2012/08/13/0813_then_t1140.jpg?abf36d44fcda22a1f7041162086f31df6a374511" />
      </div>
      <h2 class="home_text">Hello there. I'm <strong>Caleb Meacham</strong>, and I develope beautiful apps.</h2>
    </div>
  </body>
</html>

app/views/pages/work.html.erb
<!DOCTYPE html>
<html>
  <header>
  </header>
  <body>
    <h1>test</h1>
  </body>
</html>